Rails:
  Enabled: true

Metrics/LineLength:
  Max: 110

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'features/support/*'
    - 'lib/simply_record/*'
    - 'vendor/**/*'


Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false
